title: Emilio Coppa - Academic Page - Sapienza University of Rome
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Emilio Coppa - Academic Page - Sapienza University of Rome
  baseurl: "/" # the subpath of your site, e.g. /blog
  url: "http://ecoppa.github.io/" # the base hostname & protocol for your site
  
  # Build settings
  markdown: kramdown